# Generated by Django 4.2.17 on 2026-04-10 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rendezvous', '0002_consultation_date_cloture_consultation_est_cloture'),
        ('messagerie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rendezvous.consultation', verbose_name='consultation'),
        ),
    ]
