# Generated by Django 4.2.17 on 2026-04-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0002_alter_message_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio',
            field=models.FileField(blank=True, help_text='Fichier audio pour les messages vocaux.', null=True, upload_to='messages/audio/%Y/%m/', verbose_name='message vocal'),
        ),
        migrations.AddField(
            model_name='message',
            name='type_message',
            field=models.CharField(choices=[('texte', 'Texte'), ('vocal', 'Message vocal'), ('fichier', 'Fichier')], default='texte', max_length=10, verbose_name='type de message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='contenu',
            field=models.TextField(blank=True, default='', verbose_name='contenu'),
        ),
    ]
