# Generated by Django 4.2.17 on 2026-03-17 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_medecin_duree_rdv_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(verbose_name='date et heure du rendez-vous')),
                ('duree', models.PositiveIntegerField(verbose_name='durée (minutes)')),
                ('motif', models.TextField(blank=True, default='', verbose_name='motif')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('annule', 'Annulé'), ('refuse', 'Refusé'), ('termine', 'Terminé')], default='en_attente', max_length=20, verbose_name='statut')),
                ('commentaire_annulation', models.TextField(blank=True, default='', verbose_name="motif d'annulation/refus")),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='accounts.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='accounts.patient')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['-date_heure'],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('rendez_vous', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='consultation', serialize=False, to='rendezvous.rendezvous')),
                ('compte_rendu', models.TextField(blank=True, default='', verbose_name='compte rendu')),
                ('diagnostic', models.TextField(blank=True, default='', verbose_name='diagnostic')),
                ('prescription', models.TextField(blank=True, default='', verbose_name='prescription')),
                ('date_consultation', models.DateTimeField(auto_now_add=True, verbose_name='date de la consultation')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'ordering': ['-date_consultation'],
            },
        ),
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('recurrent', 'Récurrent'), ('exception', 'Exception (créneau ponctuel)'), ('indisponible', 'Indisponible (congé, absence)')], default='recurrent', max_length=20, verbose_name='type')),
                ('jour_semaine', models.IntegerField(blank=True, choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi'), (7, 'Dimanche')], help_text='1=Lundi à 7=Dimanche. Obligatoire pour les plages récurrentes.', null=True, verbose_name='jour de la semaine')),
                ('date_specifique', models.DateField(blank=True, help_text='Pour les exceptions et indisponibilités ponctuelles.', null=True, verbose_name='date spécifique')),
                ('heure_debut', models.TimeField(verbose_name='heure de début')),
                ('heure_fin', models.TimeField(verbose_name='heure de fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='accounts.medecin')),
            ],
            options={
                'verbose_name': 'Disponibilité',
                'verbose_name_plural': 'Disponibilités',
                'ordering': ['jour_semaine', 'heure_debut'],
            },
        ),
    ]
