# Generated by Django 4.2.17 on 2026-04-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendezvous', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='date_cloture',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date de clôture'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='est_cloture',
            field=models.BooleanField(default=False, verbose_name='est clôturée'),
        ),
    ]
