# Generated by Django 4.2.17 on 2026-04-28 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rendezvous', '0002_consultation_date_cloture_consultation_est_cloture'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreEnregistrement',
            fields=[
                ('rendez_vous', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pre_enregistrement', serialize=False, to='rendezvous.rendezvous')),
                ('symptomes_principaux', models.TextField(verbose_name='symptômes principaux')),
                ('debut_symptomes', models.DateField(blank=True, null=True, verbose_name='début des symptômes')),
                ('traitements_en_cours', models.TextField(blank=True, default='', verbose_name='traitements en cours')),
                ('observations', models.TextField(blank=True, default='', verbose_name='autres observations')),
                ('soumis_le', models.DateTimeField(auto_now_add=True, verbose_name='soumis le')),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
            ],
            options={
                'verbose_name': 'Préenregistrement',
                'verbose_name_plural': 'Préenregistrements',
            },
        ),
    ]
