# Generated by Django 4.2.17 on 2026-07-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendezvous', '0003_preenregistrement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('annule', 'Annulé'), ('refuse', 'Refusé'), ('termine', 'Terminé'), ('expire', 'Expiré')], default='en_attente', max_length=20, verbose_name='statut'),
        ),
    ]
