# Generated by Django 4.2.17 on 2026-07-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendezvous', '0004_alter_rendezvous_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('annule', 'Annulé'), ('refuse', 'Refusé'), ('termine', 'Terminé'), ('expire', 'Expiré')], db_index=True, default='en_attente', max_length=20, verbose_name='statut'),
        ),
        migrations.AddIndex(
            model_name='rendezvous',
            index=models.Index(fields=['medecin', 'statut', 'date_heure'], name='idx_rdv_medecin_statut_date'),
        ),
        migrations.AddIndex(
            model_name='rendezvous',
            index=models.Index(fields=['patient', 'statut', 'date_heure'], name='idx_rdv_patient_statut_date'),
        ),
    ]
