# Generated by Django 4.2.17 on 2026-03-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='question')),
                ('reponse', models.TextField(verbose_name='réponse')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('modele', models.CharField(blank=True, default='', max_length=100, verbose_name='modèle utilisé')),
            ],
            options={
                'verbose_name': 'Log chatbot',
                'verbose_name_plural': 'Logs chatbot',
                'ordering': ['-date'],
            },
        ),
    ]
