# Generated by Django 4.2.17 on 2026-03-16 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hopitaux', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adresse email')),
                ('telephone', models.CharField(max_length=20, verbose_name='téléphone')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('Autre', 'Autre')], max_length=10, verbose_name='sexe')),
                ('role', models.CharField(choices=[('patient', 'Patient'), ('medecin', 'Médecin'), ('admin_hopital', 'Administrateur Hôpital'), ('admin_general', 'Administrateur Général'), ('laborantin', 'Laborantin')], default='patient', max_length=20, verbose_name='rôle')),
                ('adresse', models.TextField(blank=True, default='', verbose_name='adresse')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos_profil/', verbose_name='photo de profil')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='email vérifié')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('hopital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnels', to='hopitaux.hopital', verbose_name='hôpital de rattachement')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Laborantin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='laborantin_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('laboratoire', models.CharField(blank=True, default='', max_length=200, verbose_name='nom du laboratoire')),
            ],
            options={
                'verbose_name': 'Laborantin',
                'verbose_name_plural': 'Laborantins',
            },
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='medecin_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('numero_ordre', models.CharField(max_length=100, unique=True, verbose_name="numéro d'ordre professionnel")),
                ('biographie', models.TextField(blank=True, default='', verbose_name='biographie')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='actif', max_length=10, verbose_name='statut')),
            ],
            options={
                'verbose_name': 'Médecin',
                'verbose_name_plural': 'Médecins',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='patient_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('contact_urgence_nom', models.CharField(max_length=150, verbose_name="nom du contact d'urgence")),
                ('contact_urgence_tel', models.CharField(max_length=20, verbose_name="téléphone du contact d'urgence")),
                ('groupe_sanguin', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='', max_length=5, verbose_name='groupe sanguin')),
                ('allergies', models.TextField(blank=True, default='', verbose_name='allergies')),
                ('numero_secu', models.CharField(blank=True, default='', max_length=50, verbose_name='numéro de sécurité sociale')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
    ]
