# Generated by Django 4.2.17 on 2026-03-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='duree_rdv_default',
            field=models.PositiveIntegerField(default=30, verbose_name="durée par défaut d'un RDV (minutes)"),
        ),
    ]
