# Generated by Django 4.2.17 on 2026-05-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_medecin_duree_rdv_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='code_activation'),
        ),
    ]
