# Generated by Django 4.2.17 on 2026-05-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_activation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='npi',
            field=models.CharField(blank=True, help_text="Numéro Personnel d'Identification (Bénin)", max_length=20, null=True, unique=True, verbose_name='NPI'),
        ),
    ]
