# Generated by Django 4.2.17 on 2026-05-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_activation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='code_activation'),
        ),
    ]
