# Generated by Django 4.2.17 on 2026-06-19 13:48
# Safe migration: adds "npi" column only if it doesn't already exist.

from django.db import migrations, models


def add_npi_if_not_exists(apps, schema_editor):
    """Add the npi column only when it is missing (idempotent)."""
    connection = schema_editor.connection
    # Introspect the table to see if the column already exists.
    columns = [
        col.name
        for col in connection.introspection.get_table_description(
            connection.cursor(), "accounts_patient"
        )
    ]
    if "npi" not in columns:
        schema_editor.execute(
            "ALTER TABLE accounts_patient "
            "ADD COLUMN npi varchar(20) NULL UNIQUE"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_activation_code'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_npi_if_not_exists,
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='patient',
                    name='npi',
                    field=models.CharField(
                        blank=True,
                        help_text="Numéro Personnel d'Identification (Bénin)",
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name='NPI',
                    ),
                ),
            ],
        ),
    ]
