# Generated by Django 4.2.17 on 2026-05-20 08:25
# ⚠️ Migration rendue vide volontairement : le champ `npi` est déjà ajouté
# dans `0004_patient_npi.py`. Cette migration existe uniquement pour
# préserver la chaîne de dépendance du merge `0007`.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_activation_code'),
    ]

    operations = [
    ]
