# Generated by Django 4.2.17 on 2026-06-19 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_patient_npi'),
        ('accounts', '0006_patient_npi'),
    ]

    operations = [
    ]
