# Generated by Django 4.2.17 on 2026-03-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hopital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='nom')),
                ('adresse', models.TextField(blank=True, default='', verbose_name='adresse')),
                ('telephone', models.CharField(blank=True, default='', max_length=20, verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='email')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
            ],
            options={
                'verbose_name': 'Hôpital',
                'verbose_name_plural': 'Hôpitaux',
                'ordering': ['nom'],
            },
        ),
    ]
