# Generated by Django 4.2.17 on 2026-03-17 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hopitaux', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('icone', models.CharField(blank=True, default='', help_text="Classe CSS, emoji ou nom d'icône", max_length=100, verbose_name='icône')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='hopital',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='hopital',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='hopital',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='hopitaux/logos/', verbose_name='logo'),
        ),
        migrations.AddField(
            model_name='hopital',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='hopital',
            name='site_web',
            field=models.URLField(blank=True, default='', verbose_name='site web'),
        ),
        migrations.AddField(
            model_name='hopital',
            name='ville',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='ville'),
        ),
        migrations.AlterField(
            model_name='hopital',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='email de contact'),
        ),
        migrations.CreateModel(
            name='DemandeAjoutService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_nouveau_service', models.CharField(blank=True, default='', max_length=100, verbose_name='nom du nouveau service')),
                ('description_nouveau_service', models.TextField(blank=True, default='', verbose_name='description du nouveau service')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_attente', max_length=20, verbose_name='statut')),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='date de la demande')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='date de traitement')),
                ('commentaire', models.TextField(blank=True, default='', verbose_name='commentaire')),
                ('demande_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_soumises', to=settings.AUTH_USER_MODEL, verbose_name='demandé par')),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_service', to='hopitaux.hopital')),
                ('service_existant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='hopitaux.service', verbose_name='service existant')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees', to=settings.AUTH_USER_MODEL, verbose_name='traité par')),
            ],
            options={
                'verbose_name': "Demande d'ajout de service",
                'verbose_name_plural': "Demandes d'ajout de service",
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='MedecinService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medecin_services', to='accounts.medecin')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_medecins', to='hopitaux.service')),
            ],
            options={
                'verbose_name': 'Service du médecin',
                'verbose_name_plural': 'Services des médecins',
                'unique_together': {('medecin', 'service')},
            },
        ),
        migrations.CreateModel(
            name='HopitalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hopital_services', to='hopitaux.hopital')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_hopitaux', to='hopitaux.service')),
            ],
            options={
                'verbose_name': "Service d'hôpital",
                'verbose_name_plural': "Services d'hôpitaux",
                'unique_together': {('hopital', 'service')},
            },
        ),
    ]
