# Generated by Django 4.2.17 on 2026-03-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopitaux', '0002_service_hopital_description_hopital_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hopitalservice',
            name='description_locale',
            field=models.TextField(blank=True, default='', verbose_name='description locale'),
        ),
    ]
