# Generated by Django 4.2.17 on 2026-03-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopitaux', '0003_hopitalservice_description_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/images/', verbose_name='image'),
        ),
    ]
