# Generated by Django 4.2.17 on 2026-04-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopitaux', '0004_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hopital',
            name='code_court',
            field=models.CharField(blank=True, help_text="Code court unique (ex: CHUC, HZPN). Utilisé dans les codes d'accès aux résultats.", max_length=10, verbose_name='code court'),
        ),
    ]
