# Generated by Django 4.2.17 on 2026-04-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopitaux', '0006_alter_hopital_code_court'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hopital',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='hopital',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='longitude'),
        ),
    ]
