# Generated by Django 4.2.17 on 2026-03-16 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('rappel_rdv', 'Rappel de rendez-vous'), ('nouveau_resultat', 'Nouveau résultat'), ('nouveau_message', 'Nouveau message'), ('compte_cree', 'Compte créé'), ('demande_service', 'Demande de service'), ('validation_service', 'Validation de service')], max_length=30, verbose_name='type')),
                ('message', models.TextField(verbose_name='message')),
                ('lu', models.BooleanField(default=False, verbose_name='lu')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name="date d'envoi")),
                ('lien', models.CharField(blank=True, default='', max_length=500, verbose_name='lien')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
