# Generated by Django 4.2.17 on 2026-03-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('rappel_rdv', 'Rappel de rendez-vous'), ('nouveau_rdv', 'Nouveau rendez-vous'), ('rdv_confirme', 'Rendez-vous confirmé'), ('rdv_refuse', 'Rendez-vous refusé'), ('rdv_annule', 'Rendez-vous annulé'), ('consultation_ajoutee', 'Consultation ajoutée'), ('nouveau_resultat', 'Nouveau résultat'), ('nouveau_message', 'Nouveau message'), ('compte_cree', 'Compte créé'), ('demande_service', 'Demande de service'), ('validation_service', 'Validation de service'), ('refus_service', 'Refus de service')], max_length=30, verbose_name='type'),
        ),
    ]
