# Generated by Django 4.2.17 on 2026-03-17 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rendezvous', '0001_initial'),
        ('accounts', '0002_medecin_duree_rdv_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='titre')),
                ('fichier', models.FileField(upload_to='resultats/%Y/%m/', verbose_name='fichier PDF')),
                ('date_analyse', models.DateField(verbose_name="date de l'analyse")),
                ('date_depot', models.DateTimeField(auto_now_add=True, verbose_name='date de dépôt')),
                ('code_acces', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name="code d'accès")),
                ('laboratoire', models.CharField(blank=True, default='', max_length=200, verbose_name='laboratoire')),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultats', to='rendezvous.consultation', verbose_name='consultation associée')),
                ('laborantin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultats_deposes', to=settings.AUTH_USER_MODEL, verbose_name='déposé par')),
                ('partages', models.ManyToManyField(blank=True, related_name='resultats_partages', to='accounts.medecin', verbose_name='partagé avec')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='accounts.patient', verbose_name='patient')),
            ],
            options={
                'verbose_name': 'Résultat',
                'verbose_name_plural': 'Résultats',
                'ordering': ['-date_depot'],
            },
        ),
    ]
