# Generated by Django 4.2.17 on 2026-04-02 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_medecin_duree_rdv_default'),
        ('hopitaux', '0005_hopital_code_court'),
        ('resultats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultat',
            name='hopital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultats', to='hopitaux.hopital', verbose_name='hôpital'),
        ),
        migrations.AddField(
            model_name='resultat',
            name='patient_email_externe',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='email externe'),
        ),
        migrations.AddField(
            model_name='resultat',
            name='patient_nom_externe',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='nom externe'),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='code_acces',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True, verbose_name="code d'accès"),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='fichier',
            field=models.FileField(blank=True, default='', upload_to='resultats/%Y/%m/', verbose_name='fichier PDF'),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='accounts.patient', verbose_name='patient'),
        ),
        migrations.CreateModel(
            name='DemandeAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_nom', models.CharField(max_length=100, verbose_name='nom du patient')),
                ('patient_prenom', models.CharField(max_length=100, verbose_name='prénom du patient')),
                ('patient_email', models.EmailField(max_length=254, verbose_name='email du patient')),
                ('patient_telephone', models.CharField(blank=True, default='', max_length=20, verbose_name='téléphone du patient')),
                ('patient_ddn', models.DateField(blank=True, null=True, verbose_name='date de naissance du patient')),
                ('type_analyse', models.CharField(help_text='Ex: NFS, Glycémie à jeun, Bilan lipidique...', max_length=255, verbose_name="type d'analyse")),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('cloture', 'Clôturé')], default='en_cours', max_length=20, verbose_name='statut')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="date d'inscription")),
                ('date_cloture', models.DateTimeField(blank=True, null=True, verbose_name='date de clôture')),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_analyse', to='hopitaux.hopital', verbose_name='hôpital')),
                ('laborantin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_inscrites', to=settings.AUTH_USER_MODEL, verbose_name='laborantin')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_analyse', to='accounts.patient', verbose_name='patient (compte E-Santé)')),
                ('resultat', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande', to='resultats.resultat', verbose_name='résultat associé')),
            ],
            options={
                'verbose_name': "Demande d'analyse",
                'verbose_name_plural': "Demandes d'analyse",
                'ordering': ['-date_inscription'],
            },
        ),
    ]
