# Generated by Django 4.2.17 on 2026-07-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultats', '0002_resultat_hopital_resultat_patient_email_externe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeanalyse',
            name='patient_email',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='email du patient'),
        ),
        migrations.AlterField(
            model_name='demandeanalyse',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('cloture', 'Clôturé')], db_index=True, default='en_cours', max_length=20, verbose_name='statut'),
        ),
        migrations.AddIndex(
            model_name='demandeanalyse',
            index=models.Index(fields=['laborantin', 'statut'], name='idx_demande_laborantin_statut'),
        ),
    ]
